require 'bundler/gem_tasks'
require 'rake/testtask'

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.test_files = FileList['test/test*.rb']
  t.verbose = true
end

require 'rubocop/rake_task'
desc 'Run RuboCop on the code'
Rubocop::RakeTask.new(:rubocop) do |task|
  task.formatters = ['progress', 'offences']
  task.patterns = ['lib/**/*.rb', 'bin/**/*', 'test/**/*.rb']
  task.fail_on_error = false
end

task :default => [:test, :rubocop]

# task :default do
#   system "gem env"
#   system "ruby --version"
#   system "pwd"
#   system "printenv"
# end
